# Generated by Django 4.2.3 on 2023-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_admin_employeedetail_manage_applyforleave_admin_emp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforleave',
            name='man',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
