# Generated by Django 4.2.3 on 2023-07-17 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0005_alter_applyforleave_man_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforleave',
            name='leave_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applyforleave',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
