# Generated by Django 4.2.3 on 2023-07-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_applyforleave_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforleave',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='applyforleave',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applyforleave',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applyforleave',
            name='reason',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applyforleave',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
