# Generated by Django 4.2.3 on 2023-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_attendancesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='days_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
