# Generated by Django 4.2.3 on 2023-07-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_attendancesummary_days_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='adhar',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='bank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='esicip',
            field=models.CharField(default='Not Applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='ifsc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='pfno',
            field=models.CharField(default='Not Applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='uan',
            field=models.CharField(default='Not Applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
