# Generated by Django 4.2.3 on 2023-07-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employeedetail_adhar_employeedetail_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='accountno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
