# Generated by Django 4.2.3 on 2023-07-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employeedetail_accountno'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='emptype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
