# Generated by Django 4.2.3 on 2023-08-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeedetail_emptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='is_present',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
