# Generated by Django 4.2.3 on 2023-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_remove_applyforleave_bimob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='biMOB',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='earnedLeaveB',
            field=models.PositiveIntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='ffcB',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='maternityLB',
            field=models.PositiveIntegerField(default=182),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='oH2B',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='oHB',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='sickLeaveB',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
