# Generated by Django 4.2.3 on 2023-08-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_employeedetail_bimob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='biMOB',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='biMOT',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='earnedLeaveB',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='earnedLeaveT',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='ffcB',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='ffcT',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='maternityLB',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='maternityLT',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='oH2B',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='oH2T',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='oHB',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='oHT',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='sickLeaveB',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='sickLeaveT',
        ),
    ]
