# Generated by Django 4.2.3 on 2023-08-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_remove_employeedetail_bimob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='biMOB',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='biMOT',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='earnedLeaveB',
            field=models.PositiveIntegerField(default=36),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='earnedLeaveT',
            field=models.PositiveIntegerField(default=36),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='ffcB',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='ffcT',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='maternityLB',
            field=models.PositiveIntegerField(default=182),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='maternityLT',
            field=models.PositiveIntegerField(default=182),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='oH2B',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='oH2T',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='oHB',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='oHT',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='sickLeaveB',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='sickLeaveT',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
