# Generated by Django 4.2.3 on 2023-08-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_employeedetail_bimob_employeedetail_bimot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='biMOB',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='biMOT',
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='biMOB',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='biMOT',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
