# Generated by Django 4.2.3 on 2023-08-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_remove_employeedetail_bimob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='paid_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='unpaid_leave',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
