# Generated by Django 4.2.3 on 2023-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_staffsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalary',
            name='salary_csv',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
