# Generated by Django 4.2.3 on 2023-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_staffsalary_salary_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalary',
            name='salary_csv',
            field=models.FileField(default=None, null=True, upload_to='csv_files/'),
        ),
    ]
