# Generated by Django 4.2.3 on 2023-08-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_remove_staffsalary_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('empcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employeedetail')),
                ('totAllottedPart', models.PositiveIntegerField(default=0)),
                ('totalPartWI0', models.PositiveIntegerField(default=0)),
                ('totalPatientsInred', models.PositiveIntegerField(default=0)),
                ('redsPer', models.PositiveIntegerField(default=0)),
                ('inc1', models.PositiveIntegerField(default=0)),
                ('amt1', models.PositiveIntegerField(default=0)),
                ('nps', models.PositiveIntegerField(default=0)),
                ('amt2', models.PositiveIntegerField(default=0)),
                ('inc_file', models.FileField(default=None, null=True, upload_to='csv_files/')),
            ],
        ),
    ]
