# Generated by Django 4.2.3 on 2023-08-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_incentive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='inc_file',
            field=models.FileField(default=None, null=True, upload_to='Inc_files/'),
        ),
    ]
