# Generated by Django 4.2.3 on 2023-08-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_alter_incentive_inc_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorIncentive',
            fields=[
                ('empcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employeedetail')),
                ('inc_file', models.FileField(default=None, null=True, upload_to='Inc_files/')),
            ],
        ),
    ]
