# Generated by Django 4.2.3 on 2023-08-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_salarycalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalculation',
            name='paid_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
