# Generated by Django 4.2.3 on 2023-08-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_salarycalculation_paid_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSalaryCalculation',
            fields=[
                ('empcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employeedetail')),
                ('empName', models.TextField(default='None')),
                ('fixPayout', models.FloatField(default=0.0)),
                ('payDays', models.PositiveIntegerField(default=0)),
                ('payDaysA', models.PositiveIntegerField(default=0)),
                ('appSalary', models.FloatField(default=0.0)),
                ('professionalFees', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'ProfessionalSalaryCalculation',
            },
        ),
    ]
