# Generated by Django 4.2.3 on 2023-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0042_rename_professional_salary_professionalsalarystructure_professional_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='sundays',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
