# Generated by Django 4.2.3 on 2023-08-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0044_professionalsalarycalculation_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnedLeaveT', models.PositiveIntegerField(default=36)),
                ('earnedLeaveB', models.PositiveIntegerField(default=36)),
                ('sickLeaveT', models.PositiveIntegerField(default=7)),
                ('sickLeaveB', models.PositiveIntegerField(default=7)),
                ('maternityLT', models.PositiveIntegerField(default=182)),
                ('maternityLB', models.PositiveIntegerField(default=182)),
                ('oH2T', models.PositiveIntegerField(default=2)),
                ('oH2B', models.PositiveIntegerField(default=2)),
                ('ffcT', models.PositiveIntegerField(default=4)),
                ('ffcB', models.PositiveIntegerField(default=4)),
                ('start_month', models.PositiveIntegerField(default=0)),
                ('start_year', models.PositiveIntegerField(default=0)),
                ('end_month', models.PositiveIntegerField(default=0)),
                ('end_year', models.PositiveIntegerField(default=0)),
                ('empcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetail')),
            ],
        ),
    ]
