# Generated by Django 4.2.3 on 2023-08-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0046_remove_employeedetail_earnedleaveb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='company_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='leavingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='adhar',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
