# Generated by Django 4.2.3 on 2023-08-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0047_employeedetail_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeedetail',
            table='EmployeeDetail',
        ),
    ]
