# Generated by Django 4.2.3 on 2023-08-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0048_alter_employeedetail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yearlyleaves',
            table='YearlyLeaves',
        ),
    ]
