# Generated by Django 4.2.3 on 2023-08-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0049_alter_yearlyleaves_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='accountno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='adhar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='ifsc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
